package com.udacity.ferfig.wheresmygas.ui;

public enum SnackBarActions {
    RETRY_CONNECTION,
    REQUEST_PERMISSIONS,
    RETRY_GET_NEARBY_STATIONS,
    RETRY_GET_NEARBY_STATIONS_IN_WIDER_AREA,
    RETRY_CONNECTION_REFRESH,
    SELECT_LOCATION,
    REQUEST_LOCATION_ACTIVATION
}
